"""empty message

Revision ID: 034f5adb3eef
Revises: 6843a026bbb3
Create Date: 2022-08-18 22:37:27.436477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '034f5adb3eef'
down_revision = '6843a026bbb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artists', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artists', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
