"""empty message

Revision ID: 1382bbbc2243
Revises: 11297c431cf3
Create Date: 2022-08-20 09:39:09.459503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1382bbbc2243'
down_revision = '11297c431cf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('artist_id', sa.Integer(), nullable=True))
    op.add_column('shows', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.alter_column('shows', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'shows', 'Artists', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.alter_column('shows', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('shows', 'start_time')
    op.drop_column('shows', 'artist_id')
    # ### end Alembic commands ###
