"""empty message

Revision ID: 15e0b9bb4537
Revises: 386aef4a7a2e
Create Date: 2022-08-20 10:11:18.240998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15e0b9bb4537'
down_revision = '386aef4a7a2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('artist_name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'shows', 'Venues', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'shows', 'Artists', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_column('shows', 'artist_name')
    # ### end Alembic commands ###
