"""empty message

Revision ID: 22e23c3a4545
Revises: ac8836dea300
Create Date: 2022-08-20 05:10:49.349329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22e23c3a4545'
down_revision = 'ac8836dea300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.add_column('shows', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.alter_column('shows', 'start_time',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'shows', 'Venues', ['venue_id'], ['id'])
    op.create_foreign_key(None, 'shows', 'Artists', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.alter_column('shows', 'start_time',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('shows', 'artist_id')
    op.drop_column('shows', 'venue_id')
    # ### end Alembic commands ###
