"""Added the many to many relation

Revision ID: 49fca4c90b44
Revises: 
Create Date: 2022-08-16 05:10:04.974300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49fca4c90b44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('venues_id', sa.Integer(), nullable=False),
    sa.Column('artists_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['artists_id'], ['Artists.id'], ),
    sa.ForeignKeyConstraint(['venues_id'], ['Venues.id'], ),
    sa.PrimaryKeyConstraint('venues_id', 'artists_id')
    )
    op.add_column('Venues', sa.Column('website', sa.String(length=500), nullable=False))
    op.add_column('Venues', sa.Column('seeking_talent', sa.Boolean(), nullable=False))
    op.add_column('Venues', sa.Column('seeking_description', sa.String(length=200), nullable=False))
    op.alter_column('Venues', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Venues', 'city',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('Venues', 'state',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('Venues', 'address',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('Venues', 'phone',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('Venues', 'image_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('Venues', 'facebook_link',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venues', 'facebook_link',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('Venues', 'image_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('Venues', 'phone',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('Venues', 'address',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('Venues', 'state',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('Venues', 'city',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('Venues', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('Venues', 'seeking_description')
    op.drop_column('Venues', 'seeking_talent')
    op.drop_column('Venues', 'website')
    op.drop_table('shows')
    # ### end Alembic commands ###
