"""empty message

Revision ID: 56d47379904e
Revises: a8bae456f85d
Create Date: 2022-08-20 06:48:23.007046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56d47379904e'
down_revision = 'a8bae456f85d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('shows_artist_id_fkey', 'shows', type_='foreignkey')
    op.drop_column('shows', 'start_time')
    op.drop_column('shows', 'artist_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('shows', sa.Column('start_time', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('shows_artist_id_fkey', 'shows', 'Artists', ['artist_id'], ['id'])
    # ### end Alembic commands ###
