"""empty message

Revision ID: 6ffed2abfc25
Revises: 1382bbbc2243
Create Date: 2022-08-20 09:44:16.602782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ffed2abfc25'
down_revision = '1382bbbc2243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('shows_artist_id_fkey', 'shows', type_='foreignkey')
    op.drop_constraint('shows_venue_id_fkey', 'shows', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('shows_venue_id_fkey', 'shows', 'Venues', ['venue_id'], ['id'])
    op.create_foreign_key('shows_artist_id_fkey', 'shows', 'Artists', ['artist_id'], ['id'])
    # ### end Alembic commands ###
