"""empty message

Revision ID: 8861eab2e9a3
Revises: c36f7464609e
Create Date: 2022-08-16 13:11:00.982004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8861eab2e9a3'
down_revision = 'c36f7464609e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artists', sa.Column('website', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artists', 'website')
    # ### end Alembic commands ###
