"""empty message

Revision ID: 8ad8df5c21f1
Revises: efe4700e17ed
Create Date: 2022-08-19 15:32:37.035133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ad8df5c21f1'
down_revision = 'efe4700e17ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('venues_id', sa.Integer(), nullable=False),
    sa.Column('artists_id', sa.Integer(), nullable=False),
    sa.Column('genre name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['artists_id'], ['Artists.id'], ),
    sa.ForeignKeyConstraint(['venues_id'], ['Venues.id'], ),
    sa.PrimaryKeyConstraint('venues_id', 'artists_id')
    )
    op.drop_column('Artists', 'genres')
    op.drop_column('Venues', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venues', sa.Column('genres', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('Artists', sa.Column('genres', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_table('genres')
    # ### end Alembic commands ###
