"""empty message

Revision ID: 8eca5eaf482a
Revises: 22e23c3a4545
Create Date: 2022-08-20 05:11:31.062910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eca5eaf482a'
down_revision = '22e23c3a4545'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shows', 'start_time',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shows', 'start_time',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
