"""empty message

Revision ID: ac8836dea300
Revises: c00006da9789
Create Date: 2022-08-20 04:47:05.238967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac8836dea300'
down_revision = 'c00006da9789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_constraint('shows_artists_id_fkey', 'shows', type_='foreignkey')
    op.drop_constraint('shows_venues_id_fkey', 'shows', type_='foreignkey')
    op.drop_column('shows', 'artists_id')
    op.drop_column('shows', 'venues_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('venues_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('shows', sa.Column('artists_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('shows_venues_id_fkey', 'shows', 'Venues', ['venues_id'], ['id'])
    op.create_foreign_key('shows_artists_id_fkey', 'shows', 'Artists', ['artists_id'], ['id'])
    op.drop_column('shows', 'id')
    # ### end Alembic commands ###
