"""empty message

Revision ID: b218d7d0dab4
Revises: 475e1739c8ae
Create Date: 2022-08-19 22:32:23.299157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b218d7d0dab4'
down_revision = '475e1739c8ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('venues_id', sa.Integer(), nullable=False),
    sa.Column('artists_id', sa.Integer(), nullable=False),
    sa.Column('genre_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['artists_id'], ['Artists.id'], ),
    sa.ForeignKeyConstraint(['venues_id'], ['Venues.id'], ),
    sa.PrimaryKeyConstraint('venues_id', 'artists_id')
    )
    op.drop_column('Venues', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venues', sa.Column('genres', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_table('genre')
    # ### end Alembic commands ###
