"""empty message

Revision ID: b2c400eee7b6
Revises: 8861eab2e9a3
Create Date: 2022-08-16 16:15:42.854235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2c400eee7b6'
down_revision = '8861eab2e9a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artists', 'website',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('Artists', 'seeking_description',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('Venues', 'website',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('Venues', 'seeking_description',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venues', 'seeking_description',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('Venues', 'website',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('Artists', 'seeking_description',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('Artists', 'website',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###
