"""empty message

Revision ID: c36f7464609e
Revises: 67960f965c64
Create Date: 2022-08-16 12:13:24.785334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c36f7464609e'
down_revision = '67960f965c64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artists', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('Artists', sa.Column('seeking_description', sa.String(length=200), nullable=False))
    op.alter_column('Venues', 'seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venues', 'seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('Artists', 'seeking_description')
    op.drop_column('Artists', 'seeking_venue')
    # ### end Alembic commands ###
