"""empty message

Revision ID: d463058c87a5
Revises: 02f7194193b8
Create Date: 2022-08-19 15:50:24.794016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd463058c87a5'
down_revision = '02f7194193b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genre', sa.Column('genre_name', sa.String(), nullable=False))
    op.drop_column('genre', 'genre name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genre', sa.Column('genre name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('genre', 'genre_name')
    # ### end Alembic commands ###
