"""empty message

Revision ID: df0c9b65c45f
Revises: 2517e4f3f2e0
Create Date: 2022-08-20 10:25:24.496920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df0c9b65c45f'
down_revision = '2517e4f3f2e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('venue_name', sa.String(), nullable=True))
    op.add_column('shows', sa.Column('artist_image_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'artist_image_link')
    op.drop_column('shows', 'venue_name')
    # ### end Alembic commands ###
