"""empty message

Revision ID: e5f5bc0027dc
Revises: 5d219ce978c4
Create Date: 2022-08-20 15:01:04.911735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5f5bc0027dc'
down_revision = '5d219ce978c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('venue_image_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'venue_image_link')
    # ### end Alembic commands ###
